CREATE CACHED TABLE CALIBRE ( 
	ID                   integer GENERATED ALWAYS AS IDENTITY  NOT NULL,
	DESCRICAO            varchar(128)   NOT NULL,
	POLVORA              numeric(6,3)   NOT NULL,
	CHUMBOS              integer   NOT NULL,
	CONSTRAINT PK_CALIBRE PRIMARY KEY ( ID )
 );

CREATE CACHED TABLE CHUMBO ( 
	ID                   numeric GENERATED ALWAYS AS IDENTITY  NOT NULL,
	DESCRICAO            varchar(128)   NOT NULL,
	QUANTIDADE           integer   NOT NULL,
	CONSTRAINT PK_CHUMBO PRIMARY KEY ( ID )
 );

CREATE CACHED TABLE ESPOLETA ( 
	ID                   numeric GENERATED ALWAYS AS IDENTITY  NOT NULL,
	DESCRICAO            varchar(128)   NOT NULL,
	QUANTIDADE           integer   NOT NULL,
	CONSTRAINT PK_ESPOLETA PRIMARY KEY ( ID )
 );

CREATE CACHED TABLE ESTOJO ( 
	ID                   numeric GENERATED ALWAYS AS IDENTITY  NOT NULL,
	DESCRICAO            varchar(128)   NOT NULL,
	QUANTIDADE           integer   NOT NULL,
	CONSTRAINT PK_ESTOJO PRIMARY KEY ( ID )
 );

CREATE CACHED TABLE MUNICAO ( 
	ID                   numeric GENERATED ALWAYS AS IDENTITY  NOT NULL,
	QUANTIDADE           integer   NOT NULL,
	CONSTRAINT PK_MUNICAO PRIMARY KEY ( ID )
 );

CREATE CACHED TABLE POLVORA ( 
	ID                   numeric GENERATED ALWAYS AS IDENTITY  NOT NULL,
	DESCRICAO            varchar(128)   NOT NULL,
	QUANTIDADE           integer   NOT NULL,
	CONSTRAINT PK_POLVORA PRIMARY KEY ( ID )
 );

CREATE CACHED TABLE PROJETIL ( 
	ID                   numeric GENERATED ALWAYS AS IDENTITY  NOT NULL,
	DESCRICAO            varchar(128)   NOT NULL,
	QUANTIDADE           integer   NOT NULL,
	CONSTRAINT PK_PROJETIL PRIMARY KEY ( ID )
 );

CREATE CACHED TABLE RECARGA ( 
	ID                   numeric GENERATED ALWAYS AS IDENTITY  NOT NULL,
	DATA                 date   NOT NULL,
	QUANTIDADE           integer   NOT NULL,
	CONSTRAINT PK_RECARGA PRIMARY KEY ( ID )
 );

CREATE CACHED TABLE CONSUMO ( 
	ID                   numeric GENERATED ALWAYS AS IDENTITY  NOT NULL,
	DATA                 date   NOT NULL,
	QUANTIDADE           integer   NOT NULL,
	CONSTRAINT PK_CONSUMO PRIMARY KEY ( ID )
 );

ALTER TABLE CONSUMO ADD CONSTRAINT ID_MUNICAO_CONSUMO FOREIGN KEY ( ID ) REFERENCES MUNICAO( ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE MUNICAO ADD CONSTRAINT ID_CALIBRE FOREIGN KEY ( ID ) REFERENCES CALIBRE( ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE RECARGA ADD CONSTRAINT ID_ESTOJO_RECARGA FOREIGN KEY ( ID ) REFERENCES ESTOJO( ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE RECARGA ADD CONSTRAINT ID_ESPOLETA_RECARGA FOREIGN KEY ( ID ) REFERENCES ESPOLETA( ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE RECARGA ADD CONSTRAINT ID_POLVORA_RECARGA FOREIGN KEY ( ID ) REFERENCES POLVORA( ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE RECARGA ADD CONSTRAINT ID_PROJETIL_RECARGA FOREIGN KEY ( ID ) REFERENCES PROJETIL( ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE RECARGA ADD CONSTRAINT ID_CHUMBO_RECARGA FOREIGN KEY ( ID ) REFERENCES CHUMBO( ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE RECARGA ADD CONSTRAINT ID_MUNICAO_RECARGA FOREIGN KEY ( ID ) REFERENCES MUNICAO( ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

