CREATE CACHED TABLE CALIBRE ( 
	ID_CALIBRE           integer GENERATED ALWAYS AS IDENTITY  NOT NULL,
	DESCRICAO            varchar(128)   NOT NULL,
	POLVORA              numeric(6,3)   NOT NULL,
	CHUMBOS              integer   NOT NULL,
	CONSTRAINT PK_CALIBRE PRIMARY KEY ( ID_CALIBRE )
 );

CREATE CACHED TABLE CHUMBO ( 
	ID_CHUMBO            numeric GENERATED ALWAYS AS IDENTITY  NOT NULL,
	DESCRICAO            varchar(128)   NOT NULL,
	QUANTIDADE           integer   NOT NULL,
	CONSTRAINT PK_CHUMBO PRIMARY KEY ( ID_CHUMBO )
 );

CREATE CACHED TABLE ESPOLETA ( 
	ID_ESPOLETA          numeric GENERATED ALWAYS AS IDENTITY  NOT NULL,
	DESCRICAO            varchar(128)   NOT NULL,
	QUANTIDADE           integer   NOT NULL,
	CONSTRAINT PK_ESPOLETA PRIMARY KEY ( ID_ESPOLETA )
 );

CREATE CACHED TABLE ESTOJO ( 
	ID_ESTOJO            numeric GENERATED ALWAYS AS IDENTITY  NOT NULL,
	DESCRICAO            varchar(128)   NOT NULL,
	QUANTIDADE           integer   NOT NULL,
	CONSTRAINT PK_ESTOJO PRIMARY KEY ( ID_ESTOJO )
 );

CREATE CACHED TABLE MUNICAO ( 
	ID_MUNICAO           numeric GENERATED ALWAYS AS IDENTITY  NOT NULL,
	QUANTIDADE           integer   NOT NULL,
	ID_MUNICAO_CALIBRE   integer   NOT NULL,
	CONSTRAINT PK_MUNICAO PRIMARY KEY ( ID_MUNICAO )
 );

CREATE INDEX IDX_MUNICAO ON MUNICAO ( ID_MUNICAO_CALIBRE );

CREATE CACHED TABLE POLVORA ( 
	ID_POLVORA           numeric GENERATED ALWAYS AS IDENTITY  NOT NULL,
	DESCRICAO            varchar(128)   NOT NULL,
	QUANTIDADE           integer   NOT NULL,
	CONSTRAINT PK_POLVORA PRIMARY KEY ( ID_POLVORA )
 );

CREATE CACHED TABLE PROJETIL ( 
	ID_PROJETIL          numeric GENERATED ALWAYS AS IDENTITY  NOT NULL,
	DESCRICAO            varchar(128)   NOT NULL,
	QUANTIDADE           integer   NOT NULL,
	CONSTRAINT PK_PROJETIL PRIMARY KEY ( ID_PROJETIL )
 );

CREATE CACHED TABLE RECARGA ( 
	ID_RECARGA           numeric GENERATED ALWAYS AS IDENTITY  NOT NULL,
	DATA                 date   NOT NULL,
	QUANTIDADE           integer   NOT NULL,
	ID_RECARGA_ESTOJO    numeric   NOT NULL,
	ID_RECARGA_ESPOLETA  numeric   NOT NULL,
	ID_RECARGA_POLVORA   numeric   NOT NULL,
	ID_RECARGA_PROJETIL  numeric   NOT NULL,
	ID_RECARGA_CHUMBO    numeric   NOT NULL,
	ID_RECARGA_MUNICAO   numeric   NOT NULL,
	CONSTRAINT PK_RECARGA PRIMARY KEY ( ID_RECARGA )
 );

CREATE INDEX IDX_RECARGA ON RECARGA ( ID_RECARGA_ESTOJO );

CREATE INDEX IDX_RECARGA_0 ON RECARGA ( ID_RECARGA_ESPOLETA );

CREATE INDEX IDX_RECARGA_1 ON RECARGA ( ID_RECARGA_POLVORA );

CREATE INDEX IDX_RECARGA_2 ON RECARGA ( ID_RECARGA_PROJETIL );

CREATE INDEX IDX_RECARGA_3 ON RECARGA ( ID_RECARGA_CHUMBO );

CREATE INDEX IDX_RECARGA_4 ON RECARGA ( ID_RECARGA_MUNICAO );

CREATE CACHED TABLE CONSUMO ( 
	ID_CONSUMO           numeric GENERATED ALWAYS AS IDENTITY  NOT NULL,
	DATA                 date   NOT NULL,
	QUANTIDADE           integer   NOT NULL,
	ID_CONSUMO_MUNICAO   numeric   NOT NULL,
	CONSTRAINT PK_CONSUMO PRIMARY KEY ( ID_CONSUMO )
 );

CREATE INDEX IDX_CONSUMO ON CONSUMO ( ID_CONSUMO_MUNICAO );

ALTER TABLE CONSUMO ADD CONSTRAINT FK_CONSUMO_MUNICAO FOREIGN KEY ( ID_CONSUMO_MUNICAO ) REFERENCES MUNICAO( ID_MUNICAO ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE MUNICAO ADD CONSTRAINT FK_MUNICAO_CALIBRE FOREIGN KEY ( ID_MUNICAO_CALIBRE ) REFERENCES CALIBRE( ID_CALIBRE ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE RECARGA ADD CONSTRAINT FK_RECARGA_ESTOJO FOREIGN KEY ( ID_RECARGA_ESTOJO ) REFERENCES ESTOJO( ID_ESTOJO ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE RECARGA ADD CONSTRAINT FK_RECARGA_ESPOLETA FOREIGN KEY ( ID_RECARGA_ESPOLETA ) REFERENCES ESPOLETA( ID_ESPOLETA ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE RECARGA ADD CONSTRAINT FK_RECARGA_POLVORA FOREIGN KEY ( ID_RECARGA_POLVORA ) REFERENCES POLVORA( ID_POLVORA ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE RECARGA ADD CONSTRAINT FK_RECARGA_PROJETIL FOREIGN KEY ( ID_RECARGA_PROJETIL ) REFERENCES PROJETIL( ID_PROJETIL ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE RECARGA ADD CONSTRAINT FK_RECARGA_CHUMBO FOREIGN KEY ( ID_RECARGA_CHUMBO ) REFERENCES CHUMBO( ID_CHUMBO ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE RECARGA ADD CONSTRAINT FK_RECARGA_MUNICAO FOREIGN KEY ( ID_RECARGA_MUNICAO ) REFERENCES MUNICAO( ID_MUNICAO ) ON DELETE NO ACTION ON UPDATE NO ACTION;

