CREATE SCHEMA PUBLIC;

CREATE TABLE CALIBRE ( 
	ID                   integer GENERATED ALWAYS AS IDENTITY  NOT NULL,
	DESCRICAO            varchar(16)   NOT NULL,
	CARGA                numeric(6,3)   NOT NULL,
	CONSTRAINT PK_CALIBRE PRIMARY KEY ( ID )
 );

CREATE TABLE CARTUCHO ( 
	ID                   numeric GENERATED ALWAYS AS IDENTITY  NOT NULL,
	DESCRICAO            varchar(64)   NOT NULL,
	QUANTIDADE           integer   NOT NULL,
	CONSTRAINT PK_TIPO_CARTUCHO_0 PRIMARY KEY ( ID )
 );

CREATE TABLE ESPOLETA ( 
	ID                   numeric GENERATED ALWAYS AS IDENTITY  NOT NULL,
	DESCRICAO            varchar(64)   NOT NULL,
	QUANTIDADE           integer   NOT NULL,
	CONSTRAINT PK_TIPO_ESPOLETA_0 PRIMARY KEY ( ID )
 );

CREATE TABLE POLVORA ( 
	ID                   numeric GENERATED ALWAYS AS IDENTITY  NOT NULL,
	DESCRICAO            varchar(64)   NOT NULL,
	QUANTIDADE           integer   NOT NULL,
	CONSTRAINT PK_TIPO_POLVORA_0 PRIMARY KEY ( ID )
 );

CREATE TABLE PROJETIL ( 
	ID                   numeric GENERATED ALWAYS AS IDENTITY  NOT NULL,
	DESCRICAO            varchar(64)   NOT NULL,
	QUANTIDADE           integer   NOT NULL,
	CONSTRAINT PK_TIPO_PROJETIL_0 PRIMARY KEY ( ID )
 );

CREATE TABLE MUNICAO ( 
	ID                   numeric GENERATED ALWAYS AS IDENTITY  NOT NULL,
	DESCRICAO            varchar(32)   NOT NULL,
	CONSTRAINT PK_MUNICAO PRIMARY KEY ( ID )
 );

CREATE TABLE RECARGA ( 
	ID                   numeric GENERATED ALWAYS AS IDENTITY  NOT NULL,
	DATA                 date   NOT NULL,
	QUANTIDADE           integer   NOT NULL,
	CONSTRAINT PK_RECARGA PRIMARY KEY ( ID )
 );

ALTER TABLE MUNICAO ADD CONSTRAINT ID_CALIBRE FOREIGN KEY ( ID ) REFERENCES CALIBRE( ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE MUNICAO ADD CONSTRAINT ID_CARTUCHO FOREIGN KEY ( ID ) REFERENCES CARTUCHO( ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE MUNICAO ADD CONSTRAINT ID_ESPOLETA FOREIGN KEY ( ID ) REFERENCES ESPOLETA( ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE MUNICAO ADD CONSTRAINT ID_POLVORA FOREIGN KEY ( ID ) REFERENCES POLVORA( ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE MUNICAO ADD CONSTRAINT ID_PROJETIL FOREIGN KEY ( ID ) REFERENCES PROJETIL( ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE RECARGA ADD CONSTRAINT ID_MUNICAO FOREIGN KEY ( ID ) REFERENCES MUNICAO( ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

