package br.com.staroski.recarga.ui;

enum Tela {

	INICIAL, //
	LISTA_CALIBRES, //
	CADASTRO_CALIBRES, //
	LISTA_CARTUCHOS, //
	CADASTRO_CARTUCHOS, //
	LISTA_CHUMBOS, //
	CADASTRO_CHUMBOS, //
	LISTA_ESPOLETAS, //
	CADASTRO_ESPOLETAS, //
	LISTA_POLVORAS, //
	CADASTRO_POLVORAS, //
	LISTA_PROJETEIS, //
	CADASTRO_PROJETEIS;
}
