package br.com.staroski.recarga.ui;

enum Tela {

	INICIAL, //
	LISTA_CALIBRES, //
	LISTA_ESTOJOS, //
	LISTA_CHUMBOS, //
	LISTA_ESPOLETAS, //
	LISTA_POLVORAS, //
	LISTA_PROJETEIS, //
	LISTA_MUNICOES, //
	LISTA_CONSUMOS, //
	LISTA_RECARGAS;
}
